tasks:
  format: prettier-eslint --write ./{test,src}/**/*.{mjs,js} --config ./.prettierrc.yml

  lint: eslint ./{test,src}/**/*.{mjs,js} --config ./.eslintrc.yml --format codeframe --fix

  test:
    - yarn start format
    - yarn start lint
    - nyc --reporter=lcov ava --tap
    - nyc report
    - nyc check-coverage

  precommit:
    - git status --porcelain
    - yarn start test
    - git add --all

  commit:
    - simple-commit-message

  release:
    - semantic-release pre
    - npm publish
    - semantic-release post
